apps/article/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views
from .views import ArticleView, TagView, ArticleDetailView, LinkView, AboutView, ArchivesView, CommentView, \
    ArticleSearchView

from rest_framework import routers

# 正在部署的应用的名称
app_name = 'article'

router = routers.DefaultRouter()  # 可以处理视图的路由器
router.register('article_api', views.ArticleAPIView)  # url进行注册

urlpatterns = [
    path('', views.index, name='index'),  # 首页
    path('article/', ArticleView.as_view(), name='article_list'),  # 文章列表
    path('article_detail/<int:article_id>/', ArticleDetailView.as_view(), name='article_detail'),  # 文章详情
    path('article_detail/<int:article_id>/comment/', CommentView.as_view(), name='article_comment'),  # 评论
    path('tag/<int:tag_id>/', TagView.as_view(), name='tag'),  # 文章标签
    path('link/', LinkView.as_view(), name='link'),  # 友情链接
    path('about_me/', AboutView.as_view(), name='about'),  # 关于
    path('archives/', ArchivesView.as_view(), name='archives'),  # 归档
    path('article/search/', ArticleSearchView.as_view(), name='article_search'),  # 搜索
    url(r'^', include(router.urls)),

]

# urlpatterns += router.urls  # 将路由器中的所有路由信息追加到django的路由列表中

apps/user/urls.py
from django.urls import path
from . import views
from .views import LoginView, RegisterView, LogoutView, MessageView
from rest_framework import routers
from django.conf.urls import url, include

# 正在部署的应用的名称
app_name = 'user'

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)


urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),  # 用户登录
    path('register/', RegisterView.as_view(), name='register'),  # 用户注册
    path('logout/', LogoutView.as_view(), name='logout'),  # 用户退出
    path('message/', MessageView.as_view(), name='message'),  # 留言

    url(r'^', include(router.urls)),

]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_title = '博客管理后台'
admin.site.site_header = '博客管理后台'

urlpatterns = [
    path('admin/', admin.site.urls),
    # 新增代码，配置app的url
    path('', include('article.urls', namespace='article')),  # 文章模块
    # 用户注册登陆页
    path('user/', include('user.urls', namespace='user')),  # 用户模块
    path('password-reset/', include('password_reset.urls')),  # 重置密码
    path('mdeditor/', include('mdeditor.urls'), ),  # 富文本
    # path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='api'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 富文本需要的配置

templates/base/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="renderer" content="webkit">
    <meta name="author" content="www.lvfengxian.cn"/>
    <meta name="viewport" content="width=device-width"/>
    <meta name="robots" content="all"/>
    <title>{% block title %}{% endblock %}</title>
    <link rel="ICON" href="{% static 'image/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/master.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/gloable.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/nprogress.css' %}"/>
    {% block link %}{% endblock %}
</head>
<body>
<!-- 引入导航栏 -->
{% include 'base/base_header.html' %}
<div class="doc-container" id="doc-container">
    {% block main %}

    {% endblock main %}
</div>
<!-- 引入注脚 -->
{% include 'base/base_footer.html' %}
<script src="{% static 'layui/layui.js' %}"></script>
<script src="{% static 'js/yss/gloable.js' %}"></script>
<script src="{% static 'js/plugins/nprogress.js' %}"></script>
<script>NProgress.start();</script>
{% block script %}

{% endblock %}
<script>
    window.onload = function () {
        NProgress.done();
    };
    (function () {
        var bp = document.createElement('script');
        var curProtocol = window.location.protocol.split(':')[0];
        if (curProtocol === 'https') {
            bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
        } else {
            bp.src = 'http://push.zhanzhang.baidu.com/push.js';
        }
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(bp, s);
    })();
</script>
</body>
</html>

templates/base/base_footer.html
<footer class="grid-footer">
    <div class="footer-fixed">
        <div class="copyright">
            <div class="info">
                <div class="contact">
                    <a href="javascript:void(0)" class="github" target="_blank"><i class="fa fa-github"></i></a>
                    <a href="https://wpa.qq.com/msgrd?v=3&uin=1105067343&site=qq&menu=yes" class="qq" target="_blank"
                       title="1105067343"><i class="fa fa-qq"></i></a>
                    <a href="https://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=1105067343@qq.com" class="email"
                       target="_blank" title="1105067343@qq.com"><i class="fa fa-envelope"></i></a>
                    <a href="javascript:void(0)" class="weixin"><i class="fa fa-weixin"></i></a>
                </div>
                <p class="mt05">
                    Copyright &copy; 2018-2018 吕奉先 All Rights Reserved V.1.0.0 蜀ICP备18008600号
                </p>
            </div>
        </div>
    </div>
</footer>

templates/base/base_header.html
{% load staticfiles %}
<div class="header">
</div>
<header class="gird-header">
    <div class="header-fixed">
        <div class="header-inner">
            <a href="javascript:void(0)" class="header-logo" id="logo">Welcome</a>
            <!-- 定义菜单里面的表单 -->
            <nav class="nav" id="nav">

                <ul>
                    <li><a href="/">首页</a></li>
                    <li><a href="{% url 'article:article_list' %}">博客</a></li>
                    <li><a href="{% url 'article:archives' %}">归档</a></li>
                    <li><a href="{% url 'user:message' %}">留言</a></li>
                    <li><a href="{% url 'article:link' %}">友链</a></li>
                    <li><a href="{% url 'article:about' %}">关于</a></li>
                    {% if user.is_authenticated %}
                        <div class="blog-user">
                            <a href="{% url 'user:logout' %}"><img
                                    src="{{ user.user_image_url }}"
                                    alt="" title=""></a>
                        </div>
                    {% else %}
                        <li><a href="{% url 'user:login' %}">登录</a></li>
                        <li><a href="{% url 'user:register' %}">注册</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</header>