apps/article/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views
from .views import ArticleView, TagView, ArticleDetailView, LinkView, AboutView, ArchivesView, CommentView, \
    ArticleSearchView

from rest_framework import routers

# 正在部署的应用的名称
app_name = 'article'

router = routers.DefaultRouter()  # 可以处理视图的路由器
router.register('article_api', views.ArticleAPIView)  # url进行注册

urlpatterns = [
    path('', views.index, name='index'),  # 首页
    path('article/', ArticleView.as_view(), name='article_list'),  # 文章列表
    path('article_detail/<int:article_id>/', ArticleDetailView.as_view(), name='article_detail'),  # 文章详情
    path('article_detail/<int:article_id>/comment/', CommentView.as_view(), name='article_comment'),  # 评论
    path('tag/<int:tag_id>/', TagView.as_view(), name='tag'),  # 文章标签
    path('link/', LinkView.as_view(), name='link'),  # 友情链接
    path('about_me/', AboutView.as_view(), name='about'),  # 关于
    path('archives/', ArchivesView.as_view(), name='archives'),  # 归档
    path('article/search/', ArticleSearchView.as_view(), name='article_search'),  # 搜索
    url(r'^', include(router.urls)),

]

# urlpatterns += router.urls  # 将路由器中的所有路由信息追加到django的路由列表中

apps/user/urls.py
from django.urls import path
from . import views
from .views import LoginView, RegisterView, LogoutView, MessageView
from rest_framework import routers
from django.conf.urls import url, include

# 正在部署的应用的名称
app_name = 'user'

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)


urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),  # 用户登录
    path('register/', RegisterView.as_view(), name='register'),  # 用户注册
    path('logout/', LogoutView.as_view(), name='logout'),  # 用户退出
    path('message/', MessageView.as_view(), name='message'),  # 留言

    url(r'^', include(router.urls)),

]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_title = '博客管理后台'
admin.site.site_header = '博客管理后台'

urlpatterns = [
    path('admin/', admin.site.urls),
    # 新增代码，配置app的url
    path('', include('article.urls', namespace='article')),  # 文章模块
    # 用户注册登陆页
    path('user/', include('user.urls', namespace='user')),  # 用户模块
    path('password-reset/', include('password_reset.urls')),  # 重置密码
    path('mdeditor/', include('mdeditor.urls'), ),  # 富文本
    # path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='api'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 富文本需要的配置

apps/article/models.py
from django.db import models
# 抽象模型类
from db.base_model import BaseModel
from mdeditor.fields import MDTextField



# class ArticleManager(models.Manager):
#     """
#     文章归档管理器
#     """
#     def distinct_date(self):  # 该管理器定义了一个distinct_date方法，目的是找出所有的不同日期
#         distinct_date_list = []  # 建立一个列表用来存放不同的日期 年-月
#         date_list = self.values('create_time')  # 根据文章字段create_time 创建时间 找出所有文章的发布时间
#         for date in date_list:  # 对所有日期进行遍历，当然这里会有许多日期是重复的，目的就是找出多少种日期
#             date = date['create_time'].strftime('%Y/%m 存档') # 取出一个日期改格式为 ‘xxx年/xxx月 存档’
#             if date not in distinct_date_list:
#                 distinct_date_list.append(date)
#         return distinct_date_list

"""上文代码建立的管理器需要在文章模型类加上语句：objects = ArticleManager()  ，然后就可以调用 distinct_date 方法了： 
archive_list = Article.objects.distinct_date()，

对比：
article_list = Article.objects.all() # 获取所有文章，获取到的是所有文章对象的一个列表

archive_list = Article.objects.distinct_date()  # 文章归档 获取到的列表格式为： xxx年/xxx月 存档"""

class Tags(BaseModel):
    """
    文章标签模型
    """
    name = models.CharField('标签名', max_length=64, help_text='标签名')

    class Meta:
        # ordering = ['-update_time', '-id']  # 排序, 负号表示为倒叙
        db_table = 'tb_tag'  # 指明数据库表名
        verbose_name = '文章标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        # str使类实例直接被打印时也会有返回值
        return self.name


# 博客文章数据模型
class Article(BaseModel):
    """
    文章模型
    """

    # 文章作者。参数 on_delete 用于指定数据删除的方式
    # django可以识别`appname.User`这种方式的引用
    author = models.ForeignKey('user.User', verbose_name='文章作者',on_delete=models.CASCADE)

    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField('标题', max_length=150, help_text='标题')

    summary = models.TextField('文章摘要', max_length=230, help_text='摘要', default='文章摘要等同于网页description内容，请务必填写...')

    content = MDTextField('内容', help_text='内容')

    views = models.IntegerField('阅览量', default=0, help_text='浏览量')

    status_choices = (
        (0, '转载'),
        (1, '原创'),
    )
    attributes = models.SmallIntegerField('是否原创', choices=status_choices, default=1)

    # IMG_LINK = '/image/two.jpg'
    # image_url = models.CharField('图片链接', max_length=200, default=IMG_LINK, help_text='图片链接')
    image_url = models.ImageField(upload_to='article/%Y%m%d/', verbose_name='文章图片')

    # 定义分类标签的外键字段, 一般外键字段定义在`一对多`中多的一方
    tag = models.ForeignKey('Tags', verbose_name='文章标签',on_delete=models.SET_NULL, null=True)

    # 实现文章归档
    # objects = ArticleManager()  # 在模型中使用自定义的管理器

    class Meta:
        # ordering = ['-update_time', '-id']
        db_table = 'tb_articles'
        verbose_name = '博客文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class FriendLink(BaseModel):
    """
    友情链接
    """
    status_choices = (
        (0, '无效'),
        (1, '有效'),
    )
    name = models.CharField('网站名称', max_length=50)
    description = models.CharField('网站描述', max_length=100, blank=True)
    link = models.URLField('友链地址', help_text='请填写http或https开头的完整形式地址')
    logo = models.URLField('网站LOGO', help_text='请填写http或https开头的完整形式地址', blank=True)
    create_date = models.DateTimeField('创建时间', auto_now_add=True)
    is_active = models.SmallIntegerField('是否有效', choices=status_choices, default=1)
    is_show = models.BooleanField('是否首页展示', default=False)

    class Meta:
        db_table = 'tb_FriendLink'
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name
        # ordering = ['create_date']

    def __str__(self):
        return self.name


class Comments(BaseModel):
    """
    评论模型
    """
    content = models.TextField('内容', help_text='内容')

    author = models.ForeignKey('user.User', verbose_name='评论人',on_delete=models.CASCADE, null=True)
    # CASCADE级联删除, 若新闻文章被删除, 那么评论也将被删除
    articles = models.ForeignKey('Article', verbose_name='所属文章',on_delete=models.CASCADE)

    # 本项目涉及二级评论，修改Comments模型，添加一个parent字段
    parent = models.ForeignKey('self', verbose_name='父评论',on_delete=models.CASCADE, null=True, blank=True, )

    # rep_to = models.ForeignKey('self', verbose_name='回复',
    #                            blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        # ordering = ['-update_time', '-id']
        db_table = 'tb_comments'
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        # django会帮我们在生成迁移的时候自动添加id字段
        return self.content[:20]

    def to_dict_data(self):
        comment_dict = {
            'news_id': self.articles_id,
            'content_id': self.id,
            'content': self.content,
            'author': self.author.username,
            'create_time': self.create_time.astimezone().strftime('%Y年%m月%d日 %H:%M'),
            'parent': self.parent.to_dict_data() if self.parent else None
        }
        # comment_dict = Comments.objects.to_dict_data() # 获取到的字典格式为： comment_dict
        return comment_dict


class HotArticles(BaseModel):
    """
    新闻文章模型
    """
    news = models.OneToOneField('Article', verbose_name='文章',on_delete=models.CASCADE)
    priority = models.IntegerField('优先级', help_text='首页热门文章优先级')

    class Meta:
        # ordering = ['-update_time', '-id']  # 排序
        db_table = "tb_hot_articles"  # 指明数据库表名
        verbose_name = "热门文章"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return '<热门新闻{}>'.format(self.id)


class RecommendRead(BaseModel):
    """
    推荐阅读
    """
    recommend_title = models.CharField('标题', max_length=150, help_text='标题')
    recommend_url = models.URLField('文章地址', help_text='请填写推荐文章的地址')

    class Meta:
        db_table = 'tb_recommend_read'
        verbose_name = '推荐阅读'
        verbose_name_plural = verbose_name

    def __str__(self):
        # django会帮我们在生成迁移的时候自动添加id字段
        return self.recommend_title

templates/article/article_list.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load my_filters_and_tags %}
{% block title %}吕奉先:)文章列表{% endblock %}
{% block link %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
{% endblock %}

<!-- 预留具体页面的位置 -->
{% block main %}
    <div class="container-fixed">
        <div class="col-content">
            <div class="inner">
                <article class="article-list bloglist" id="LAY_bloglist">
                    {% for article in articles %}
                        <section class="article-item zoomIn article">
                            {#                        语法在获取moidel中字段带有choices的字段属性时；{{course.get_属性名_display}}#}
                            <div class="fc-flag">{{ article.get_attributes_display }}</div>
                            <h5 class="title">
                                <a href="{% url 'article:article_detail' article.id %}">{{ article.title }}</a>
                                <span class="fc-blue">【{{ article.create_time|timesince_zh }}】</span>
                            </h5>
                            <div class="time">
                                <span class="day">{{ article.create_time | date:'j' }}</span>
                                <span class="month fs-18">{{ article.create_time | date:'n' }}<span
                                        class="fs-14">月</span></span>
                                <span class="year fs-18 ml10">{{ article.create_time | date:'Y' }}</span>
                            </div>
                            <div class="content">
                                <a href="{% url 'article:article_detail' article.id %}" class="cover img-light">
                                    <img src="{{ article.image_url.url }}">
                                </a>
                                {#                                其中的|slice:'100'是Django的过滤器语法，表示取出正文的前100个字符，避免摘要太长。#}
                                {{ article.summary |slice:'100' }}
                            </div>
                            <div class="read-more">
                                <a href="{% url 'article:article_detail' article.id %}" class="fc-black f-fwb" style="right: 20px;position: absolute;
                                ">阅读全文</a>
                            </div>
                            <aside class="f-oh footer">
                                <div class="f-fl tags">
                                    <span class="fa fa-tags fs-16"></span>
                                    <a href="{% url 'article:tag' article.tag.id %}"
                                       class="tag">{{ article.tag.name }}</a>
                                </div>
                                <div class="f-fr">
									<span class="read">
										<i class="fa fa-eye fs-16" style="color: #2196f3"></i>
										<i class="num">{{ article.views }}</i>
									</span>
                                    <span class="ml20">
										<i class="fa fa-comments fs-16" style="color: #ff5722"></i>
										<a href="javascript:void(0)"
                                           class="num fc-grey">{{ article.comments_set.count }}</a>
									</span>
                                </div>
                            </aside>
                        </section>
                    {% endfor %}
                    {# 实现分页标签的代码 #}
                    {# 这里使用 bootstrap 渲染页面 #}
                    <div id="pages" class="text-center">
                        <nav>
                            <ul class="pagination">
                                <li>
                                    {% if articles.has_previous %}
                                        <a class='active' href="?page={{ articles.previous_page_number }}">上一页</a>
                                    {% endif %}

                                    <span>
                    Page {{ articles.number }} of {{ articles.paginator.num_pages }}</span>

                                    {% if articles.has_next %}
                                        <a class='active' href="?page={{ articles.next_page_number }}">下一页</a>
                                    {% endif %}
                                </li>
                            </ul>
                        </nav>
                    </div>

                </article>
            </div>
        </div>
        <div class="col-other">
            <div class="inner">
                <div class="other-item" id="categoryandsearch">
                    <div class="search">
                        <label class="search-wrap">
                            <form action="/article/search/">
                            <input type="text" name='q' id="searchtxt" placeholder="输入关键字搜索"/>
                            <span class="search-icon">
{#					                <i class="fa fa-search"></i>#}
                                    <input type="image" src="{% static 'image/search.png' %}" style="height: 100%;">
					            </span>
                            </form>
                        </label>
                        <ul class="search-result"></ul>
                    </div>
                    <ul class="category mt20" id="category">
                        <li data-index="0" class="slider"></li>
                        <li data-index="1"><a href="{% url 'article:article_list' %}">全部文章</a></li>
                        <li data-index="2"><a href="{% url 'article:tag' 2 %}">python</a></li>
                        <li data-index="3"><a href="{% url 'article:tag' 4 %}">django</a></li>
                        <li data-index="4"><a href="{% url 'article:tag' 5 %}">docker</a></li>
                        <li data-index="5"><a href="{% url 'article:tag' 6 %}">数据分析</a></li>
                        <li data-index="6"><a href="{% url 'article:tag' 7 %}">其它</a></li>
                    </ul>
                </div>
                <!--右边悬浮 平板或手机设备显示-->
                <div class="category-toggle"><i class="layui-icon">&#xe603;</i></div>
                <div class="article-category">
                    <div class="article-category-title">网站导航</div>
                    <a href="{% url 'article:index' %}">首页</a>
                    <a href="{% url 'article:article_list' %}">博客</a>
                    <a href="{% url 'user:message' %}">留言</a>
                    <a href="{% url 'article:link' %}">友链</a>
                    <a href="{% url 'article:about' %}">关于</a>
                    <div class="f-cb"></div>
                </div>
                <!--遮罩-->
                <div class="blog-mask animated layui-hide"></div>
                <div class="other-item">
                    <h5 class="other-item-title">热门文章</h5>
                    <div class="inner">
                        <ul class="hot-list-article">
                            {% for hot in hot_articles %}
                                <li><a href="{% url 'article:article_detail' hot.id %}">{{ hot.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="other-item">
                    <h5 class="other-item-title">推荐阅读</h5>
                    <div class="inner">
                        <ul class="hot-list-article">
                            {% for recommend_read in recommend_reads %}
                            <li><a href="{{ recommend_read.recommend_url }}">{{ recommend_read.recommend_title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="other-item">
                    <h5 class="other-item-title">最近访客</h5>
                    <div class="inner">
                        <dl class="vistor">
                            <dd><a href="javasript:;"><img
                                    src="https://thirdqq.qlogo.cn/qqapp/101465933/72388EA977643E8F97111222675720B1/100"><cite>Anonymous</cite></a>
                            </dd>
                            <dd><a href="javasript:;"><img
                                    src="https://thirdqq.qlogo.cn/qqapp/101465933/342F777E313DDF5CCD6E3E707BB0770B/100"><cite>Dekstra</cite></a>
                            </dd>
                            <dd><a href="javasript:;"><img
                                    src="https://thirdqq.qlogo.cn/qqapp/101465933/EA5D00A72C0C43ECD8FC481BD274DEEC/100"><cite>惜i</cite></a>
                            </dd>
                            <dd><a href="javasript:;"><img
                                    src="https://thirdqq.qlogo.cn/qqapp/101465933/EF18CEC98150D2442183AA30F05AAD7B/100"><cite>↙Aㄨ计划
                                ◆莪↘</cite></a></dd>
                            <dd><a href="javasript:;"><img
                                    src="https://thirdqq.qlogo.cn/qqapp/101465933/3D8D91AD2BAFD36F5AC494DA51E270E6/100"><cite>.</cite></a>
                            </dd>
                            <dd><a href="javasript:;"><img
                                    src="https://thirdqq.qlogo.cn/qqapp/101465933/B745A110DAB712A0E6C5D0B633E905D3/100"><cite>Lambert.</cite></a>
                            </dd>
                            <dd><a href="javasript:;"><img
                                    src="https://thirdqq.qlogo.cn/qqapp/101465933/E9BA3A2499EC068B7917B9EF45C4D13C/100"><cite>64ღ</cite></a>
                            </dd>
                            <dd><a href="javasript:;"><img
                                    src="https://thirdqq.qlogo.cn/qqapp/101465933/09F92966169272DD7DD9999E709A0204/100"><cite>doBoor</cite></a>
                            </dd>
                            <dd><a href="javasript:;"><img
                                    src="https://thirdqq.qlogo.cn/qqapp/101465933/59991D53192643A1A651383847332EB6/100"><cite>毛毛小妖</cite></a>
                            </dd>
                            <dd><a href="javasript:;"><img
                                    src="https://thirdqq.qlogo.cn/qqapp/101465933/FF34F311DDC43E2AF63BE897BCA24F05/100"><cite>NULL</cite></a>
                            </dd>
                            <dd><a href="javasript:;"><img
                                    src="https://thirdqq.qlogo.cn/qqapp/101465933/59AA25A7627284AE62C8E6EBDC6FE417/100"><cite>吓一跳</cite></a>
                            </dd>
                            <dd><a href="javasript:;"><img
                                    src="https://thirdqq.qlogo.cn/qqapp/101465933/28B021E0F5AF0A4B9B781A24329FE897/100"><cite>如初</cite></a>
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}
{% block script %}
    <script src="{% static 'js/yss/article.js' %}"></script>
{% endblock %}


<!-- container end -->